import Head from 'next/head'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'
import { createRoot } from 'react-dom/client'
import { Button, Table, Input, Spin } from 'antd'
import axios from 'axios'

// 当前正在请求的数量
let requestCount = 0

// 显示loading
function showLoading () {
  if (requestCount === 0) {
    var dom = document.createElement('div')
    dom.setAttribute('id', 'loading')
    document.body.appendChild(dom)
    createRoot(dom).render(<Spin size="large"/>)
  }
  requestCount++
}

// 隐藏loading
function hideLoading () {
  requestCount--
  if (requestCount === 0) {
    document.body.removeChild(document.getElementById('loading'))
  }
}

export default function Home() {
  const [data, setData] = useState([]);
  const [searchVal, setSearchVal] = useState('');
  const [pager, setPager] = useState({
    current: 1,
    pageSize: 3000,
  });
  
  const fetchData = async (params = {}) => {
    showLoading()
    const { data } = await axios.get('/api/douban', { params, timeout: 1000000 })
    console.log(data.list)
    hideLoading()
    setData(data.list.map((item, index) => ({ ...item, index })))
  }

  const handleSearch = () => {
    console.log('???', searchVal)
    fetchData({
      searchVal
    })
  }

  const handlePageChange = (page) => {
    fetchData({
      page,
    })
    setPager({
      ...pager,
      current: page,
    })
  }

  useEffect(() => {
    fetchData()
  }, [])

  const columns = [
    {
      title: '内容',
      dataIndex: 'title',
      key: 'title',
      render: (text, record) => <a href={record.url} target="_blank">{text}</a>
    },
    {
      title: '名字',
      dataIndex: 'username',
      key: 'username',
    },
    {
      title: '时间',
      dataIndex: 'time',
      key: 'time',
    },
  ]
  return (
    <>
      <Head>
        <title>dbzf</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.searchBox}>
          <Input placeholder='请输入筛选内容' value={searchVal} onChange={(e) => setSearchVal(e.target.value)} />
          <Button onClick={() => handleSearch()}>获取接口</Button> 
          <Button onClick={() => fetchData({ type: 'all' })}>重新爬取</Button>
        </div>
        <div style={{width: '100%'}}>
          <Table
            dataSource={data}
            columns={columns}
            rowKey={'index'}
            expandable={{
              expandedRowRender: (record) => <div>
                {record.content}
                {
                  record.imgList.map((url, index) => <img src={url} key={index} />)
                }
              </div>,
              defaultExpandAllRows: true,
            }}
            pagination={{
              pageSize: 3000
              // total: 300,
              // ...pager,
              // onChange: handlePageChange
            }}
          />
        </div>
      </main>
    </>
  )
}
