import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'
import { createRoot } from 'react-dom/client'
import { Button, Table, Input, Spin } from 'antd'
import axios from 'axios'
import { useRouter } from 'next/router'

export default function Detail() {
  
  const { query } = useRouter()
  
  return (
    <>
      <Head>
        <title>dbzf</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        { query.id }
      </main>
    </>
  )
}
